version: '3'
services:
  db:
    image: mysql:latest
    container_name: fd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: food_delivery
      MYSQL_USER: food_delivery
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge