spring:

  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: food_delivery
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate

# JWT
jwt:
  header: token
  issuer: fooddelivery
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiration: 3600

logging:
  logback:
    rollingpolicy:
      max-history: 60
      total-size-cap: 3GB