spring:

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false

    jpa:
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
          default_batch_fetch_size: 1000

      hibernate:
        ddl-auto: validate

# JWT
jwt:
  header: token
  issuer: himin
  client-secret: ${JWT_CLIENT_SECRET}
  expiry-seconds: 60

logging:
  file:
    path: ./logs
    name: app-prod
  logback:
    rollingpolicy:
      max-history: 60
      total-size-cap: 3GB